import { ShadcnDemo } from "../../components/ShadcnDemo";

export default function ShadcnPage() {
  return (
    <>
      <h1>shadcn adapter + popover shell</h1>
      <p>
        <code>trim/TrimShell.tsx</code> below was generated by a real <code>trim init</code> run
        against this fixture&apos;s project root (which has a real <code>components.json</code>{" "}
        and local <code>components/ui/button.tsx</code> / <code>components/ui/popover.tsx</code>).
        It imports those two components directly — Trim&apos;s own runtime renders no shadcn
        chrome itself.
      </p>
      <ShadcnDemo />
    </>
  );
}
