import { ShadcnBaseDemo } from "../../components/ShadcnBaseDemo";

export default function ShadcnBasePage() {
  return (
    <>
      <h1>shadcn adapter + popover shell (Base UI backend)</h1>
      <p>
        <code>trim/TrimShell.tsx</code> below was generated by a real <code>trim init</code> run
        against <code>integrations/shadcn-base/</code> (its own <code>components.json</code> with{" "}
        <code>&quot;style&quot;: &quot;base-vega&quot;</code>, and local{" "}
        <code>components/ui/button.tsx</code> / <code>components/ui/popover.tsx</code> using Base
        UI&apos;s <code>render</code>-prop composition). Same generator as{" "}
        <code>/shadcn</code>&apos;s Radix variant — different composition syntax, detected purely
        from this project&apos;s own shadcn config, never guessed.
      </p>
      <ShadcnBaseDemo />
    </>
  );
}
