"use client";

// Generated by Trim (`trim init`, ui.adapter: "shadcn", ui.shell: "popover",
// shadcn primitive backend: Base UI).
// Host-owned from this point on — Trim's runtime has no idea this file
// exists or that shadcn is involved (ui.adapter !== "vanilla" always
// resolves to a zero-wrapper passthrough at runtime; see
// src/react/shell/resolve.ts): it only ever renders
// <Trim.Panel config={trimConfig} />. Uses your project's own shadcn
// Button + Popover components (see components.json's "style"/"ui" alias) —
// remove or hand-edit freely, `trim init` never rewrites this file after
// creation.
//
// Base UI composes triggers via a `render` prop, never Radix's slot-based
// composition prop — PopoverTrigger renders its OWN element (here, the
// Button passed via `render`) with these children as that element's
// content, so there is exactly one interactive element in the DOM, never a
// <button> nested inside another.
import { Button } from "@base-ui-fixture/components/ui/button";
import { Popover, PopoverContent, PopoverTrigger } from "@base-ui-fixture/components/ui/popover";
import { Panel } from "@theharborproject/trim/react";
import trimConfig from "./trim.config";

export function TrimShell() {
  return (
    <Popover>
      <PopoverTrigger render={<Button variant="outline" />}>Accessibility</PopoverTrigger>
      <PopoverContent align="end">
        <Panel config={trimConfig} />
      </PopoverContent>
    </Popover>
  );
}
