// Generated by Trim. Updated by the Trim CLI — do not hand-edit; `trim new
// control` regenerates this file whenever a Trim-managed control's schema
// changes. Entries are kept in lexical key order.
// @trim-managed-schema {"version":1,"settings":[{"key":"example","kind":"boolean","defaultValue":false}]}
//
// One shared controller for every Trim-managed control — never one per
// *.trim.ts file. A boolean Trim-managed setting is backed by a two-value
// string schema under the hood; see bindingEntry's comment in this
// generator for why, and note it changes nothing about this file's own
// public shape: trimSettings.<key> is always a genuine TrimBinding of the
// control's real value type.
import { createTrimController, controller, callback } from "@theharborproject/trim";

const trimSettingsController = createTrimController(
  {
    example: ["true", "false"],
  },
  {
    example: "false",
  },
  "trim-settings",
);

export const trimSettings = {
  example: callback<boolean>(
    () => controller(trimSettingsController, "example").get() === "true",
    (value) => controller(trimSettingsController, "example").set(value ? "true" : "false"),
    (listener) => controller(trimSettingsController, "example").subscribe((value) => listener(value === "true")),
  ),
};
