// Generated by Trim. Host-owned — customize freely; the Trim CLI only
// edits this file's `groups` array structurally, via `trim attach`.
import { defineTrimConfig } from "@theharborproject/trim/react";

export default defineTrimConfig({
  ui: {
    adapter: "vanilla",
    shell: "popover",
  },
  layout: "sections",
  groups: [
    {
      id: "example",
      label: "Example",
      controls: ["example"],
    },
  ],
});
