// Generated by Trim. Host-owned — Trim itself never rewrites this file
// after creation; only `trim new control` creates it.
// Trim-managed state: `binding` comes from ../trim.settings.ts's host-owned controller (see that file — one shared controller for every Trim-managed control).
import { defineSegmentedControl } from "@theharborproject/trim";
import { trimSettings } from "../trim.settings";

export default defineSegmentedControl({
  id: "animations",
  label: "Animations",
  is_unique: false,
  options: [{ value: "full", label: "Full" }, { value: "reduced", label: "Reduced" }],
  binding: trimSettings.animations,
});
