// Generated by Trim. Host-owned — Trim itself never rewrites this file
// after creation; only `trim new control` creates it.
// Project-managed state: `binding` points at state this project already owns — Trim never duplicates or takes ownership of it.
import { defineBooleanControl } from "@theharborproject/trim";
import { callback } from "@theharborproject/trim";
import { getContrast, setContrast, subscribeContrast } from "../../host/contrast-store";

export default defineBooleanControl({
  id: "contrast",
  label: "High contrast",
  binding: callback(getContrast, setContrast, subscribeContrast),
});
