// Generated by Trim. Updated by the Trim CLI — do not hand-edit;
// `trim new control` appends to this file automatically. Entries are kept
// in lexical id order, so regeneration is deterministic regardless of the
// order controls were added in.
import animations from "./controls/animations.trim";
import contrast from "./controls/contrast.trim";
import theme from "./controls/theme.trim";

export const trimControls = [
  animations,
  contrast,
  theme,
] as const;
