// Generated by Trim. Updated by the Trim CLI — do not hand-edit;
// `trim new control` appends to this file automatically. Entries are kept
// in lexical id order, so regeneration is deterministic regardless of the
// order controls were added in.
import example from "./controls/example.trim";

export const trimControls = [
  example,
] as const;
