// Generated by Trim. Updated by the Trim CLI — do not hand-edit; `trim new
// control` regenerates this file whenever a Trim-managed control's schema
// changes. Entries are kept in lexical key order.
// @trim-managed-schema {"version":1,"settings":[{"key":"high-contrast","kind":"boolean","defaultValue":false},{"key":"starter","kind":"boolean","defaultValue":false},{"key":"text-size","kind":"segmented","options":["small","default","large"],"defaultValue":"default"}]}
//
// One shared controller for every Trim-managed control — never one per
// *.trim.ts file. A boolean Trim-managed setting is backed by a two-value
// string schema under the hood; see bindingEntry's comment in this
// generator for why, and note it changes nothing about this file's own
// public shape: trimSettings.<key> is always a genuine TrimBinding of the
// control's real value type.
import { createTrimController, controller, callback } from "@theharborproject/trim";

const trimSettingsController = createTrimController(
  {
    "high-contrast": ["true", "false"],
    starter: ["true", "false"],
    "text-size": ["small", "default", "large"],
  },
  {
    "high-contrast": "false",
    starter: "false",
    "text-size": "default",
  },
  "trim-settings",
);

export const trimSettings = {
  highContrast: callback<boolean>(
    () => controller(trimSettingsController, "high-contrast").get() === "true",
    (value) => controller(trimSettingsController, "high-contrast").set(value ? "true" : "false"),
    (listener) => controller(trimSettingsController, "high-contrast").subscribe((value) => listener(value === "true")),
  ),
  starter: callback<boolean>(
    () => controller(trimSettingsController, "starter").get() === "true",
    (value) => controller(trimSettingsController, "starter").set(value ? "true" : "false"),
    (listener) => controller(trimSettingsController, "starter").subscribe((value) => listener(value === "true")),
  ),
  textSize: controller(trimSettingsController, "text-size"),
};
