// Generated by Trim. Host-owned — customize freely; the Trim CLI only
// edits this file's `groups` array structurally, via `trim attach`.
import { defineTrimConfig } from "@theharborproject/trim/react";
import { trimRenderers } from "./trim.renderers";

export default defineTrimConfig({
  ui: {
    adapter: "shadcn",
    shell: "popover",
    renderers: trimRenderers,
  },
  layout: "sections",
  groups: [
    {
      id: "starter",
      label: "Example",
      controls: ["starter"],
    },
    {
      id: "text",
      label: "Text",
      controls: ["text-size"],
    },
    {
      id: "contrast",
      label: "Contrast",
      controls: [
        "high-contrast",
      ],
    },
  ],
});
