"use client";

// Generated by Trim (`trim init`, ui.adapter: "shadcn", ui.shell: "popover").
// Host-owned from this point on — Trim's runtime has no idea this file
// exists or that shadcn is involved.

import { Button } from "@/components/ui/button";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";

import { Panel } from "@theharborproject/trim/react";
import trimConfig from "./trim.config";

export function TrimShell() {
  return (
    <div
      style={{
        position: "fixed",
        right: "1rem",
        bottom: "1rem",
        zIndex: 50,
      }}
    >
      <Popover>
        <PopoverTrigger asChild>
          <Button variant="outline">Accessibility</Button>
        </PopoverTrigger>

        <PopoverContent align="end">
          <Panel config={trimConfig} />
        </PopoverContent>
      </Popover>
    </div>
  );
}