// Generated by Trim. Host-owned — Trim itself never rewrites this file
// after creation; only `trim new control` creates it.
// Trim-managed state: `binding` comes from ../trim.settings.ts's host-owned controller (see that file — one shared controller for every Trim-managed control).
import { defineBooleanControl } from "@theharborproject/trim";
import { trimSettings } from "../trim.settings";

export default defineBooleanControl({
  id: "example",
  label: "Example control",
  binding: trimSettings.example,
});
