"use client";

// Generated by Trim (`trim init`). Mount <TrimPanel/> wherever the panel
// should be reachable from — this file already carries its own
// "use client", so it can be rendered directly from a Server Component
// (e.g. a Next.js RootLayout) with no extra client-boundary work needed.
// Wraps the generated <TrimShell/> (trim/TrimShell.tsx) in <Trim.Registry>:
// TrimShell only renders <Panel>, it does not register trimControls itself.
// Host-owned from here on — trim init only (re)writes this file when its
// content doesn't already match, exactly like every other generated file.
import { Trim } from "@theharborproject/trim/react";
import { trimControls } from "./trim.manifest";
import { TrimShell } from "./TrimShell";

export function TrimPanel() {
  return (
    <Trim.Registry controls={trimControls}>
      <TrimShell />
    </Trim.Registry>
  );
}
